export const hiraganaWords = [
    { kana: "いえ", romaji: ["i", "e"] },
    { kana: "いいえ", romaji: ["i", "i", "e"] },
    { kana: "おう", romaji: ["o", "u"] },
    { kana: "いう", romaji: ["i", "u"] },
    { kana: "あう", romaji: ["a", "u"] },
    { kana: "うえ", romaji: ["u", "e"] },
    { kana: "あおい", romaji: ["a", "o", "i"] },
    { kana: "あき", romaji: ["a", "ki"] },
    { kana: "きく", romaji: ["ki", "ku"] },
    { kana: "かく", romaji: ["ka", "ku"] },
    { kana: "あかい", romaji: ["a", "ka", "i"] },
    { kana: "いく", romaji: ["i", "ku"] },
    { kana: "ここ", romaji: ["ko", "ko"] },
    { kana: "あく", romaji: ["a", "ku"] },
    { kana: "おおきい", romaji: ["o", "o", "ki", "i"] },
    { kana: "くうこう", romaji: ["ku", "u", "ko", "u"] },
    { kana: "えき", romaji: ["e", "ki"] },
    { kana: "かこ", romaji: ["ka", "ko"] },
    { kana: "こえ", romaji: ["ko", "e"] },
    { kana: "おく", romaji: ["o", "ku"] },
    { kana: "かう", romaji: ["ka", "u"] },
    { kana: "いけ", romaji: ["i", "ke"] },
    { kana: "くうき", romaji: ["ku", "u", "ki"] },
    { kana: "かお", romaji: ["ka", "o"] },
];