export const hiraganaWords = [
    { kana: "いえ", romaji: ["i", "e"], kanji: "家" },
    { kana: "いいえ", romaji: ["i", "i", "e"], kanji: "" },
    { kana: "おう", romaji: ["o", "u"], kanji: "王" },
    { kana: "いう", romaji: ["i", "u"], kanji: "言う" },
    { kana: "あう", romaji: ["a", "u"], kanji: "会う" },
    { kana: "うえ", romaji: ["u", "e"], kanji: "上" },
    { kana: "あおい", romaji: ["a", "o", "i"], kanji: "青い" },
    { kana: "あき", romaji: ["a", "ki"], kanji: "秋" },
    { kana: "きく", romaji: ["ki", "ku"], kanji: "聞く" },
    { kana: "かく", romaji: ["ka", "ku"], kanji: "書く" },
    { kana: "あかい", romaji: ["a", "ka", "i"], kanji: "赤い" },
    { kana: "いく", romaji: ["i", "ku"], kanji: "行く" },
    { kana: "ここ", romaji: ["ko", "ko"] },
    { kana: "あく", romaji: ["a", "ku"], kanji: "開く" },
    { kana: "おおきい", romaji: ["o", "o", "ki", "i"], kanji: "大きい" },
    { kana: "くうこう", romaji: ["ku", "u", "ko", "u"], kanji: "空港" },
    { kana: "えき", romaji: ["e", "ki"], kanji: "駅" },
    { kana: "かこ", romaji: ["ka", "ko"], kanji: "過去" },
    { kana: "こえ", romaji: ["ko", "e"], kanji: "声" },
    { kana: "おく", romaji: ["o", "ku"], kanji: "置く" },
    { kana: "かう", romaji: ["ka", "u"], kanji: "買う" },
    { kana: "いけ", romaji: ["i", "ke"], kanji: "池" },
    { kana: "くうき", romaji: ["ku", "u", "ki"], kanji: "空気" },
    { kana: "かお", romaji: ["ka", "o"], kanji: "顔" },
    { kana: "しあい", romaji: ["shi", "a", "i"], kanji: "試合" },
    { kana: "かさ", romaji: ["ka", "sa"], kanji: "傘" },
    { kana: "あし", romaji: ["a", "shi"], kanji: "足" },
    { kana: "すき", romaji: ["su", "ki"], kanji: "好き" },
    { kana: "こし", romaji: ["ko", "shi"], kanji: "腰" },
    { kana: "くさ", romaji: ["ku", "sa"], kanji: "草" },
    { kana: "さす", romaji: ["sa", "su"], kanji: "指す" },
    { kana: "しかし", romaji: ["shi", "ka", "shi"], kanji: "" },
    { kana: "せき", romaji: ["se", "ki"], kanji: "席" },
    { kana: "すし", romaji: ["su", "shi"], kanji: "" },
    { kana: "うそ", romaji: ["u", "so"], kanji: "嘘" },
    { kana: "うし", romaji: ["u", "shi"], kanji: "牛" },
    { kana: "しお", romaji: ["shi", "o"], kanji: "塩" },
    { kana: "あさ", romaji: ["a", "sa"], kanji: "朝" },
    { kana: "すこし", romaji: ["su", "ko", "shi"], kanji: "" },
    { kana: "さく", romaji: ["sa", "ku"], kanji: "咲く" },
    { kana: "いす", romaji: ["i", "su"], kanji: "" },
    { kana: "けさ", romaji: ["ke", "sa"], kanji: "今朝" },
    { kana: "あそこ", romaji: ["a", "so", "ko"], kanji: "" },
    { kana: "たつ", romaji: ["ta", "tsu"], kanji: "立つ" },
    { kana: "こと", romaji: ["ko", "to"], kanji: "事" },
    { kana: "いち", romaji: ["i", "chi"], kanji: "一" },
    { kana: "あつい", romaji: ["a", "tsu", "i"], kanji: "暑い" },
    { kana: "さとう", romaji: ["sa", "to", "u"], kanji: "砂糖" },
    { kana: "ちかてつ", romaji: ["chi", "ka", "te", "tsu"], kanji: "地下鉄" },
    { kana: "あした", romaji: ["a", "shi", "ta"], kanji: "明日" },
    { kana: "とけい", romaji: ["to", "ke", "i"], kanji: "時計" },
    { kana: "おとこ", romaji: ["o", "to", "ko"], kanji: "男" },
    { kana: "くち", romaji: ["ku", "chi"], kanji: "口" },
    { kana: "つち", romaji: ["tsu", "chi"], kanji: "土" },
    { kana: "たかい", romaji: ["ta", "ka", "i"], kanji: "高い" },
    { kana: "きた", romaji: ["ki", "ta"], kanji: "北" },
    { kana: "つくえ", romaji: ["tsu", "ku", "e"], kanji: "机" },
    { kana: "ちかい", romaji: ["chi", "ka", "i"], kanji: "近い" },
    { kana: "たいせつ", romaji: ["ta", "i", "se", "tsu"], kanji: "大切" },
    { kana: "うたう", romaji: ["u", "ta", "u"], kanji: "歌う" },
    { kana: "ことし", romaji: ["ko", "to", "shi"], kanji: "今年" },
    { kana: "おとうと", romaji: ["o", "to", "u", "to"], kanji: "弟" },
    { kana: "くつした", romaji: ["ku", "tsu", "shi", "ta"], kanji: "靴下" },
    { kana: "ちいさい", romaji: ["chi", "i", "sa", "i"], kanji: "小さい" },
    { kana: "そうして", romaji: ["so", "u", "shi", "te"], kanji: "" },
    { kana: "しち", romaji: ["shi", "chi"], kanji: "七" },
    { kana: "つかう", romaji: ["tsu", "ka", "u"], kanji: "使う" },
    { kana: "いたい", romaji: ["i", "ta", "i"], kanji: "痛い" },
    { kana: "そと", romaji: ["so", "to"], kanji: "外" },
    { kana: "とおい", romaji: ["to", "o", "i"], kanji: "遠い" },
    { kana: "きって", romaji: ["ki", "-t", "te"], kanji: "" },
    { kana: "いぬ", romaji: ["i", "nu"], kanji: "犬" },
    { kana: "ねこ", romaji: ["ne", "ko"], kanji: "猫" },
    { kana: "なに", romaji: ["na", "ni"], kanji: "何" },
    { kana: "さかな", romaji: ["sa", "ka", "na"], kanji: "魚" },
    { kana: "その", romaji: ["so", "no"], kanji: "" },
    { kana: "おなか", romaji: ["o", "na", "ka"], kanji: "お腹" },
    { kana: "あね", romaji: ["a", "ne"], kanji: "姉" },
    { kana: "しぬ", romaji: ["shi", "nu"], kanji: "死ぬ" },
    { kana: "せなか", romaji: ["se", "na", "ka"], kanji: "背中" },
    { kana: "かなしい", romaji: ["ka", "na", "shi", "i"], kanji: "悲しい" },
    { kana: "なか", romaji: ["na", "ka"], kanji: "中" },
    { kana: "きのこ", romaji: ["ki", "no", "ko"], kanji: "" },
    { kana: "きのう", romaji: ["ki", "no", "u"], kanji: "昨日" },
    { kana: "にく", romaji: ["ni", "ku"], kanji: "肉" },
    { kana: "おとな", romaji: ["o", "to", "na"], kanji: "大人" },
    { kana: "にし", romaji: ["ni", "shi"], kanji: "西" },
    { kana: "なく", romaji: ["na", "ku"], kanji: "泣く" },
    { kana: "あに", romaji: ["a", "ni"], kanji: "兄" },
    { kana: "おかね ", romaji: ["o", "ka", "ne"], kanji: "お金" },
    { kana: "あなた ", romaji: ["a", "na", "ta"], kanji: "" },
    { kana: "はい", romaji: ["ha", "i"], kanji: "" },
    { kana: "ひと", romaji: ["hi", "to"], kanji: "人" },
    { kana: "ふとい", romaji: ["fu", "to", "i"], kanji: "太い" },
    { kana: "へた", romaji: ["he", "ta"], kanji: "下手" },
    { kana: "ふうとう", romaji: ["fu", "u", "to", "u"], kanji: "封筒" },
    { kana: "ひこうき", romaji: ["hi", "ko", "u", "ki"], kanji: "飛行機" },
    { kana: "はち", romaji: ["ha", "chi"], kanji: "八" },
    { kana: "そふ", romaji: ["so", "fu"], kanji: "祖父" },
    { kana: "はなす", romaji: ["ha", "na", "su"], kanji: "話す" },
    { kana: "へいし", romaji: ["he", "i", "shi"], kanji: "兵士" },
    { kana: "ふたつ", romaji: ["fu", "ta", "tsu"], kanji: "二つ" },
    { kana: "ほね", romaji: ["ho", "ne"], kanji: "骨" },
    { kana: "ひくい", romaji: ["hi", "ku", "i"], kanji: "低い" },
    { kana: "ほし", romaji: ["ho", "shi"], kanji: "星" },
    { kana: "たいふう", romaji: ["ta", "i", "fu", "u"], kanji: "台風" },
    { kana: "ふく", romaji: ["fu", "ku"], kanji: "服" },
    { kana: "はな", romaji: ["ha", "na"], kanji: "花" },
    { kana: "ほそい", romaji: ["ho", "so", "i"], kanji: "細い" },
    { kana: "あめ", romaji: ["a", "me"], kanji: "雨" },
    { kana: "ほほえむ", romaji: ["ho", "ho", "e", "mu"], kanji: "微笑む" },
    { kana: "みち", romaji: ["mi", "chi"], kanji: "道" },
    { kana: "あたま", romaji: ["a", "ta", "ma"], kanji: "頭" },
    { kana: "ねむい", romaji: ["ne", "mu", "i"], kanji: "眠い" },
    { kana: "あまい", romaji: ["a", "ma", "i"], kanji: "甘い" },
    { kana: "みなみ", romaji: ["mi", "na", "mi"], kanji: "南" },
    { kana: "まち", romaji: ["ma", "chi"], kanji: "町・街" },
    { kana: "ひみつ", romaji: ["hi", "mi", "tsu"], kanji: "秘密" },
    { kana: "いま", romaji: ["i", "ma"], kanji: "今" },
    { kana: "はさみ", romaji: ["ha", "sa", "mi"], kanji: "" },
    { kana: "のみもの", romaji: ["no", "mi", "mo", "no"], kanji: "飲み物" },
    { kana: "むし", romaji: ["mu", "shi"], kanji: "虫" },
    { kana: "こめ", romaji: ["ko", "me"], kanji: "米" },
    { kana: "おもい", romaji: ["o", "mo", "i"], kanji: "重い" },
    { kana: "にもつ", romaji: ["ni", "mo", "tsu"], kanji: "荷物" },
    { kana: "うま", romaji: ["u", "ma"], kanji: "馬" },
    { kana: "さむい", romaji: ["sa", "mu", "i"], kanji: "寒い" },
    { kana: "なまえ", romaji: ["na", "ma", "e"], kanji: "名前" },
    { kana: "はじめまして", romaji: ["ha", "ji", "me", "ma", "shi", "te"], kanji: "" },
    { kana: "まいにち", romaji: ["ma", "i", "ni", "chi"], kanji: "毎日" },
    { kana: "かみ", romaji: ["ka", "mi"], kanji: "紙" },
    { kana: "つめたい", romaji: ["tsu", "me", "ta", "i"], kanji: "冷たい" },
    { kana: "みせ", romaji: ["mi", "se"], kanji: "店" },
    { kana: "むこう", romaji: ["mu", "ko", "u"], kanji: "向こう" },
    { kana: "ゆうめい", romaji: ["yu", "u", "me", "i"], kanji: "有名" },
    { kana: "やった", romaji: ["ya", "-t", "ta"], kanji: "" },
    { kana: "よむ", romaji: ["yo", "mu"], kanji: "読む" },
    { kana: "やさしい", romaji: ["ya", "sa", "shi", "i"], kanji: "優しい" },
    { kana: "ひつよう", romaji: ["hi", "tsu", "yo", "u"], kanji: "必要" },
    { kana: "ふゆ", romaji: ["fu", "yu"], kanji: "冬" },
    { kana: "やすい", romaji: ["ya", "su", "i"], kanji: "安い" },
    { kana: "へや", romaji: ["he", "ya"], kanji: "部屋" },
    { kana: "たいよう", romaji: ["ta", "i", "yo", "u"], kanji: "太陽" },
    { kana: "つよい", romaji: ["tsu", "yo", "i"], kanji: "強い" },
    { kana: "やさい", romaji: ["ya", "sa", "i"], kanji: "野菜" },
    { kana: "はやく", romaji: ["ha", "ya", "ku"], kanji: "早く" },
    { kana: "ゆき", romaji: ["yu", "ki"], kanji: "雪" },
    { kana: "なつやすみ", romaji: ["na", "tsu", "ya", "su", "mi"], kanji: "夏休み" },
    { kana: "やま", romaji: ["ya", "ma"], kanji: "山" },
    { kana: "ようふく", romaji: ["yo", "u", "fu", "ku"], kanji: "洋服" },
    { kana: "かゆい", romaji: ["ka", "yu", "i"], kanji: "" },
    { kana: "ゆっくり", romaji: ["yu", "-k", "ku", "ri"], kanji: "" },
    { kana: "むらさき", romaji: ["mu", "ra", "sa", "ki"], kanji: "紫" },
    { kana: "となり", romaji: ["to", "na", "ri"], kanji: "隣" },
    { kana: "よる", romaji: ["yo", "ru"], kanji: "夜" },
    { kana: "こころ", romaji: ["ko", "ko", "ro"], kanji: "心" },
    { kana: "ならう", romaji: ["na", "ra", "u"], kanji: "習う" },
    { kana: "はれる", romaji: ["ha", "re", "ru"], kanji: "晴れる" },
    { kana: "つまらない", romaji: ["tsu", "ma", "ra", "na", "i"], kanji: "" },
    { kana: "けむり", romaji: ["ke", "mu", "ri"], kanji: "煙" },
    { kana: "きれい", romaji: ["ki", "re", "i"], kanji: "" },
    { kana: "あたらしい", romaji: ["a", "ta", "ra", "shi", "i"], kanji: "新しい" },
    { kana: "うれしい", romaji: ["u", "re", "shi", "i"], kanji: "嬉しい" },
    { kana: "おもしろい", romaji: ["o", "mo", "shi", "ro", "i"], kanji: "面白い" },
    { kana: "れきし", romaji: ["re", "ki", "shi"], kanji: "歴史" },
    { kana: "いろ", romaji: ["i", "ro"], kanji: "色" },
    { kana: "とりにく", romaji: ["to", "ri", "ni", "ku"], kanji: "とり肉" },
    { kana: "ぬるい", romaji: ["nu", "ru", "i"], kanji: "温い" },
    { kana: "そら", romaji: ["so", "ra"], kanji: "空" },
    { kana: "こたえる", romaji: ["ko", "ta", "e", "ru"], kanji: "答える" },
    { kana: "くもり", romaji: ["ku", "mo", "ri"], kanji: "曇り" },
    { kana: "みせる", romaji: ["mi", "se", "ru"], kanji: "見せる" },
    { kana: "からい", romaji: ["ka", "ra", "i"], kanji: "辛い" },
    { kana: "うしろ", romaji: ["u", "shi", "ro"], kanji: "後ろ" },
    { kana: "つかれる", romaji: ["tsu", "ka", "re", "ru"], kanji: "疲れる" },
    { kana: "ひろい", romaji: ["hi", "ro", "i"], kanji: "広い" },
    { kana: "うまれる", romaji: ["u", "ma", "re", "ru"], kanji: "生まれる" },
    { kana: "はたらく", romaji: ["ha", "ta", "ra", "ku"], kanji: "働く" },
    { kana: "わたし", romaji: ["wa", "ta", "shi"], kanji: "私" },
    { kana: "しあわせ", romaji: ["shi", "a", "wa", "se"], kanji: "幸せ" },
    { kana: "うん", romaji: ["u", "n"], kanji: "" },
    { kana: "かわ", romaji: ["ka", "wa"], kanji: "川" },
    { kana: "ほん", romaji: ["ho", "n"], kanji: "本" },
    { kana: "わらう", romaji: ["wa", "ra", "u"], kanji: "笑う" },
    { kana: "たいへん", romaji: ["ta", "i", "he", "n"], kanji: "大変" },
    { kana: "やわらかい", romaji: ["ya", "wa", "ra", "ka", "i"], kanji: "" },
    { kana: "わかる", romaji: ["wa", "ka", "ru"], kanji: "分かる" },
    { kana: "おんな", romaji: ["o", "n", "na"], kanji: "女" },
    { kana: "にほん", romaji: ["ni", "ho", "n"], kanji: "日本" },
    { kana: "すわる", romaji: ["su", "wa", "ru"], kanji: "座る" },
    { kana: "おはよう", romaji: ["o", "ha", "yo", "u"], kanji: "" },
    { kana: "かわいい", romaji: ["ka", "wa", "i", "i"], kanji: "" },
    { kana: "けっこん", romaji: ["ke", "-k", "ko", "n"], kanji: "結婚" },
    { kana: "こうえん", romaji: ["ko", "u", "e", "n"], kanji: "公園" },
    { kana: "こわれる", romaji: ["ko", "wa", "re", "ru"], kanji: "壊れる" },
    { kana: "まいねん", romaji: ["ma", "i", "ne", "n"], kanji: "毎年" },
    { kana: "ほんとう", romaji: ["ho", "n", "to", "u"], kanji: "本当" },
    { kana: "わかい", romaji: ["wa", "ka", "i"], kanji: "若い" },
    { kana: "さん", romaji: ["sa", "n"], kanji: "三" },
    { kana: "てんき", romaji: ["te", "n", "ki"], kanji: "天気" },
    { kana: "わるい", romaji: ["wa", "ru", "i"], kanji: "悪い" },
    { kana: "みんな", romaji: ["mi", "n", "na"], kanji: "" },
    { kana: "にわ", romaji: ["ni", "wa"], kanji: "庭" },
    { kana: "しつもん", romaji: ["shi", "tsu", "mo", "n"], kanji: "質問" },
    { kana: "あぶない", romaji: ["a", "bu", "na", "i"], kanji: "危ない" },
    { kana: "いそがしい", romaji: ["i", "so", "ga", "shi", "i"], kanji: "忙しい" },
    { kana: "ちゅうごくご", romaji: ["chu", "u", "go", "ku", "go"], kanji: "中国語" },
    { kana: "いりぐち", romaji: ["i", "ri", "gu", "chi"], kanji: "入り口" },
    { kana: "ごぜん", romaji: ["go", "ze", "n"], kanji: "午前" },
    { kana: "だいがく", romaji: ["da", "i", "ga", "ku"], kanji: "大学" },
    { kana: "かぞく", romaji: ["ka", "zo", "ku"], kanji: "家族" },
    { kana: "はっぱ", romaji: ["ha", "-p", "pa"], kanji: "葉っぱ" },
    { kana: "りょうり", romaji: ["ryo", "u", "ri"], kanji: "料理" },
    { kana: "たべもの", romaji: ["ta", "be", "mo", "no"], kanji: "食べ物" },
    { kana: "ざっし", romaji: ["za", "-s", "shi"], kanji: "雑誌" },
    { kana: "しょうじょ", romaji: ["sho", "u", "jo"], kanji: "少女" },
    { kana: "きょうだい", romaji: ["kyo", "u", "da", "i"], kanji: "兄弟" },
    { kana: "いちばん", romaji: ["i", "chi", "ba", "n"], kanji: "一番" },
    { kana: "きっぷ", romaji: ["ki", "-p", "pu"], kanji: "切符" },
    { kana: "しょくぶつ", romaji: ["sho", "ku", "bu", "tsu"], kanji: "植物" },
    { kana: "ぎゅうにゅう", romaji: ["gyu", "u", "nyu", "u"], kanji: "牛乳" },
    { kana: "ひゃく", romaji: ["hya", "ku"], kanji: "百" },
    { kana: "でんわ", romaji: ["de", "n", "wa"], kanji: "電話" },
    { kana: "すばらしい", romaji: ["su", "ba", "ra", "shi", "i"], kanji: "" },
    { kana: "じょうほう", romaji: ["jo", "u", "ho", "u"], kanji: "情報" },
    { kana: "しょうゆ", romaji: ["sho", "u", "yu"], kanji: "" },
    { kana: "べんきょう", romaji: ["be", "n", "kyo", "u"], kanji: "勉強" },
    { kana: "びょうき", romaji: ["byo", "u", "ki"], kanji: "病気" },
    { kana: "じしょ", romaji: ["ji", "sho"], kanji: "辞書" },
    { kana: "あそぶ", romaji: ["a", "so", "bu"], kanji: "遊ぶ" },
    { kana: "きょう", romaji: ["kyo", "u"], kanji: "今日" },
    { kana: "しゃかい", romaji: ["sha", "ka", "i"], kanji: "社会" },
    { kana: "よろこび", romaji: ["yo", "ro", "ko", "bi"], kanji: "喜び" },
    { kana: "ぶんぽう", romaji: ["bu", "n", "po", "u"], kanji: "文法" },
    { kana: "らいしゅう", romaji: ["ra", "i", "shu", "u"], kanji: "来週" },
    { kana: "しょうねん", romaji: ["sho", "u", "ne", "n"], kanji: "少年" },
    { kana: "きゅう", romaji: ["kyu", "u"], kanji: "九" },
    { kana: "こども", romaji: ["ko", "do", "mo"], kanji: "子供" },
    { kana: "たんじょうび", romaji: ["ta", "n", "jo", "u", "bi"], kanji: "誕生日" },
    { kana: "ちゃいろ", romaji: ["cha", "i", "ro"], kanji: "茶色" },
];