export const katakanaWords = [
    { kana: "ウイ", romaji: ["u", "i"] },
    { kana: "アイ", romaji: ["a", "i"] },
    { kana: "エアー", romaji: ["e", "a", "-a"] },
    { kana: "キー", romaji: ["ki", "-i"] },
    { kana: "ケア", romaji: ["ke", "a"] },
    { kana: "アーク", romaji: ["a", "-a", "ku"] },
    { kana: "エコカー", romaji: ["e", "ko", "ka", "-a"] },
    { kana: "オーケー", romaji: ["o", "-o", "ke", "-e"] },
    { kana: "カー", romaji: ["ka", "-a"] },
    { kana: "ケーキ", romaji: ["ke", "-e", "ki"] },
    { kana: "サーカス", romaji: ["sa", "-a", "ka", "su"] },
    { kana: "シー", romaji: ["shi", "-i"] },
    { kana: "ケース", romaji: ["ke", "-e", "su"] },
    { kana: "セクシー", romaji: ["se", "ku", "shi", "-i"] },
    { kana: "アクセス", romaji: ["a", "ku", "se", "su"] },
    { kana: "キス", romaji: ["ki", "su"] },
    { kana: "ソース", romaji: ["so", "-o", "su"] },
    { kana: "シーソー", romaji: ["shi", "-i", "so", "-o"] },
    { kana: "エース", romaji: ["e", "-e", "su"] },
    { kana: "アイス", romaji: ["a", "i", "su"] },
    { kana: "ツアー", romaji: ["tsu", "a", "-a"] },
    { kana: "ターキー", romaji: ["ta", "-a", "ki", "-i"] },
    { kana: "チケット", romaji: ["chi", "ke", "-t", "to"] },
    { kana: "トイ", romaji: ["to", "i"] },
    { kana: "スーツ", romaji: ["su", "-u", "tsu"] },
    { kana: "カート", romaji: ["ka", "-a", "to"] },
    { kana: "コーチ", romaji: ["ko", "-o", "chi"] },
    { kana: "タイ", romaji: ["ta", "i"] },
    { kana: "サッカー", romaji: ["sa", "-k", "ka", "-a"] },
    { kana: "コート", romaji: ["ko", "-o", "to"] },
    { kana: "サーキット", romaji: ["sa", "-a", "ki", "-t", "to"] },
    { kana: "タッチ", romaji: ["ta", "-c", "chi"] },
    { kana: "エイト", romaji: ["e", "i", "to"] },
    { kana: "カット", romaji: ["ka", "-t", "to"] },
    { kana: "シート", romaji: ["shi", "-i", "to"] },
    { kana: "ツー", romaji: ["tsu", "-u"] },
    { kana: "タクシー", romaji: ["ta", "ku", "shi", "-i"] },
    { kana: "アート", romaji: ["a", "-a", "to"] },
    { kana: "ナース", romaji: ["na", "-a", "su"] },
    { kana: "ノート", romaji: ["no", "-o", "to"] },
    { kana: "カヌー", romaji: ["ka", "nu", "-u"] },
    { kana: "ニー", romaji: ["ni", "-i"] },
    { kana: "ナイト", romaji: ["na", "i", "to"] },
    { kana: "エスニック", romaji: ["e", "su", "ni", "-k", "ku"] },
    { kana: "スノー", romaji: ["su", "no", "-o"] },
    { kana: "ネクタイ", romaji: ["ne", "ku", "ta", "i"] },
    { kana: "コネクタ", romaji: ["ko", "ne", "ku", "ta"] },
    { kana: "スニーカー", romaji: ["su", "ni", "-i", "ka", "-a"] },
    { kana: "コーナー", romaji: ["ko", "-o", "na", "-a"] },
    { kana: "ニート", romaji: ["ni", "-i", "to"] },
    { kana: "ノック", romaji: ["no", "-k", "ku"] },
    { kana: "ノック", romaji: ["no", "-k", "ku"] },
    { kana: "セーフ", romaji: ["se", "-e", "fu"] },
    { kana: "ハイテク", romaji: ["ha", "i", "te", "ku"] },
    { kana: "ホット", romaji: ["ho", "-t", "to"] },
    { kana: "ハウス", romaji: ["ha", "u", "su"] },
    { kana: "コーヒー", romaji: ["ko", "-o", "hi", "-i"] },
    { kana: "ヘアー", romaji: ["he", "a", "-a"] },
    { kana: "ハーフ", romaji: ["ha", "-a", "fu"] },
    { kana: "ハート", romaji: ["ha", "-a", "to"] },
    { kana: "ヒーター", romaji: ["hi", "-i", "ta", "-a"] },
    { kana: "ホッケー", romaji: ["ho", "-k", "ke", "-e"] },
    { kana: "ナイフ", romaji: ["na", "i", "fu"] },
    { kana: "ハット", romaji: ["ha", "-t", "to"] },
    { kana: "ハニー", romaji: ["ha", "ni", "-i"] },
    { kana: "シネマ", romaji: ["shi", "ne", "ma"] },
    { kana: "ハム", romaji: ["ha", "mu"] },
    { kana: "コミックス", romaji: ["ko", "mi", "-k", "ku", "su"] },
    { kana: "タイマー", romaji: ["ta", "i", "ma", "-a"] },
    { kana: "アニメ", romaji: ["a", "ni", "me"] },
    { kana: "チーム", romaji: ["chi", "-i", "mu"] },
    { kana: "ハーモニー ", romaji: ["ha", "-a", "mo", "ni", "-i"] },
    { kana: "ホーム", romaji: ["ho", "-o", "mu"] },
    { kana: "トマト", romaji: ["to", "ma", "to"] },
    { kana: "クモ", romaji: ["ku", "mo"] },
    { kana: "アイテム", romaji: ["a", "i", "te", "mu"] },
    { kana: "メーカー", romaji: ["me", "-e", "ka", "-a"] },
    { kana: "メモ", romaji: ["me", "mo"] },
    { kana: "ミート", romaji: ["mi", "-i", "to"] },
    { kana: "マーク", romaji: ["ma", "-a", "ku"] },
    { kana: "アトム", romaji: ["a", "to", "mu"] },
    { kana: "マスコミ", romaji: ["ma", "su", "ko", "mi"] },
    { kana: "マーケット", romaji: ["ma", "-a", "ke", "-t", "to"] },
    { kana: "カスタム", romaji: ["ka", "su", "ta", "mu"] },
    { kana: "エコノミー", romaji: ["e", "ko", "no", "mi", "-i"] },
    { kana: "ヨット", romaji: ["yo", "-t", "to"] },
    { kana: "タイヤ", romaji: ["ta", "i", "ya"] },
    { kana: "ユーモア", romaji: ["yu", "-u", "mo", "a"] },
    { kana: "イヤー", romaji: ["i", "ya", "-a"] },
    { kana: "ユニット", romaji: ["yu", "ni", "-t", "to"] },
    { kana: "ユース", romaji: ["yu", "-u", "su"] },
    { kana: "ヒーロー", romaji: ["hi", "-i", "ro", "-o"] },
    { kana: "ホテル", romaji: ["ho", "te", "ru"] },
    { kana: "カメラ", romaji: ["ka", "me", "ra"] },
    { kana: "クリスマス", romaji: ["ku", "ri", "su", "ma", "su"] },
    { kana: "ライフ", romaji: ["ra", "i", "fu"] },
    { kana: "セラミック", romaji: ["se", "ra", "mi", "-k", "ku"] },
    { kana: "アメリカ", romaji: ["a", "me", "ri", "ka"] },
    { kana: "リアル", romaji: ["ri", "a", "ru"] },
    { kana: "カラフル", romaji: ["ka", "ra", "fu", "ru"] },
    { kana: "エラー", romaji: ["e", "ra", "-a"] },
    { kana: "ストーリー", romaji: ["su", "to", "-o", "ri", "-i"] },
    { kana: "アラーム", romaji: ["a", "ra", "-a", "mu"] },
    { kana: "リクエスト", romaji: ["ri", "ku", "-e", "su", "to"] },
    { kana: "ユーロ", romaji: ["yu", "-u", "ro", "-o"] },
    { kana: "ミイラ", romaji: ["mi", "i", "ra"] },
    { kana: "アクセサリー", romaji: ["a", "ku", "se", "sa", "ri", "-i"] },
    { kana: "ウール", romaji: ["u", "-u", "ru"] },
    { kana: "ロッカー", romaji: ["ro", "-k", "ka", "-a"] },
    { kana: "トイレ", romaji: ["to", "i", "re"] },
    { kana: "ルームメイト", romaji: ["ru", "-u", "mu", "me", "i", "to"] },
    { kana: "カロリー", romaji: ["ka", "ro", "ri", "-i"] },
    { kana: "クリーム", romaji: ["ku", "ri", "-i", "mu"] },
    { kana: "タオル", romaji: ["ta", "o", "ru"] },
    { kana: "メートル", romaji: ["me", "-e", "to", "ru"] },
    { kana: "モノクローム", romaji: ["mo", "no", "ku", "ro", "-o", "mu"] },
    { kana: "クレーター", romaji: ["ku", "re", "-e", "ta", "-a"] },
    { kana: "トラ", romaji: ["to", "ra"] },
    { kana: "フラワー", romaji: ["fu", "ra", "wa", "-a"] },
    { kana: "アンケート", romaji: ["a", "n", "ke", "-e", "to"] },
    { kana: "キッチン", romaji: ["ki", "-c", "chi", "n"] },
    { kana: "ワイフ", romaji: ["wa", "i", "fu"] },
    { kana: "エアコン", romaji: ["e", "a", "ko", "n"] },
    { kana: "ワイン", romaji: ["wa", "i", "n"] },
    { kana: "ヒント", romaji: ["hi", "n", "to"] },
    { kana: "セメント", romaji: ["se", "me", "n", "to"] },
    { kana: "ワイヤ", romaji: ["wa", "i", "ya"] },
    { kana: "マラソン", romaji: ["ma", "ra", "so", "n"] },
    { kana: "サラリーマン", romaji: ["sa", "ra", "ri", "-i", "ma", "n"] },
    { kana: "インターネット", romaji: ["i", "n", "ta", "-a", "ne", "-t", "to"] },
    { kana: "ワーク", romaji: ["wa", "-a", "ku"] },
    { kana: "ハンサム", romaji: ["ha", "n", "sa", "mu"] },
    { kana: "タワー", romaji: ["ta", "wa", "-a"] },
    { kana: "サイン", romaji: ["sa", "i", "n"] },
    { kana: "ワクチン", romaji: ["wa", "ku", "chi", "n"] },
    { kana: "レモン", romaji: ["re", "mo", "n"] },
    { kana: "ホワイト", romaji: ["ho", "wa", "i", "to"] },
    { kana: "ハンカチ", romaji: ["ha", "n", "ka", "chi"] },
    { kana: "カーテン", romaji: ["ka", "-a", "te", "n"] },
    { kana: "カーテン", romaji: ["ka", "-a", "te", "n"] },
    { kana: "アカデミー", romaji: ["a", "ka", "de", "mi", "-i"] },
    { kana: "バッグ", romaji: ["ba", "-g", "gu"] },
    { kana: "チャレンジ", romaji: ["cha", "re", "n", "ji"] },
    { kana: "パソコン", romaji: ["pa", "so", "ko", "n"] },
    { kana: "ウェーター ", romaji: ["we", "-e", "ta", "-a"] },
    { kana: "シャワー", romaji: ["sha", "wa", "-a"] },
    { kana: "キューブ", romaji: ["kyu", "-u", "bu"] },
    { kana: "ジーパン", romaji: ["ji", "-i", "pa", "n"] },
    { kana: "チェック", romaji: ["che", "-k", "ku"] },
    { kana: "ミーティング", romaji: ["mi", "-i", "ti", "n", "gu"] },
    { kana: "ワンダフル", romaji: ["wa", "n", "da", "fu", "ru"] },
    { kana: "ショップ", romaji: ["sho", "-p", "pu"] },
    { kana: "ジャーナリスト", romaji: ["ja", "-a", "na", "ri", "su", "to"] },
    { kana: "ズボン", romaji: ["zu", "bo", "n"] },
    { kana: "ミュージアム", romaji: ["myu", "-u", "ji", "a", "mu"] },
    { kana: "フォーク", romaji: ["fo", "-o", "ku"] },
    { kana: "エンジン", romaji: ["e", "n", "ji", "n"] },
    { kana: "ホリデイ", romaji: ["ho", "ri", "de", "i"] },
    { kana: "フィッシュ", romaji: ["fi", "-s", "shu"] },
    { kana: "ポケット", romaji: ["po", "ke", "-t", "to"] },
    { kana: "ガソリン", romaji: ["ga", "so", "ri", "n"] },
    { kana: "ジュース", romaji: ["ju", "-u", "su"] },
    { kana: "ブレックファースト", romaji: ["bu", "re", "-k", "ku", "fa", "-a", "su", "to"] },
    { kana: "ボディー", romaji: ["bo", "di", "-i"] },
    { kana: "ハイウェー", romaji: ["ha", "i", "we", "e"] },
    { kana: "アドレス", romaji: ["a", "do", "re", "su"] },
    { kana: "ゲーム", romaji: ["ge", "-e", "mu"] },
    { kana: "パスポート", romaji: ["pa", "su", "po", "-o", "to"] },
    { kana: "ペンキ", romaji: ["pe", "n", "ki"] },
    { kana: "インタビュー", romaji: ["i", "n", "ta", "byu", "-u"] },
    { kana: "イリュージョン", romaji: ["i", "ryu", "-u", "jo", "n"] },
    { kana: "ギャラリー", romaji: ["gya", "ra", "ri", "-i"] },
    { kana: "ヴァイオリン", romaji: ["va", "i", "o", "ri", "n"] },
    { kana: "ソング", romaji: ["so", "n", "gu"] },
];